title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          text:
            label: Project description
            type: textarea
            help: See our content styleguide
            required: true
          year:
            before: Finished
            type: number
            min: 2000
            width: 1/2
          category:
            type: select
            options:
              - Product Design
              - Editorial
              - Photography
            width: 1/2
          client:
            type: text
            width: 1/2
            icon: user
          link:
            type: url
            width: 1/2
          tags:
            type: tags
          location:
            type: locator

  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        image:
          ratio: 1/1
